version: '{build}'
branches:
  only:
  - master
  - /^windows-test.*/
os: Visual Studio 2013

environment:
  BOOST_ROOT: '\libraries\boost'
  CMAKE_PREFIX_PATH: '\qt\5.5\msvc2013'
  BOOST_LIBRARYDIR: '\libraries\boost\lib32-msvc-12.0'

# Before build: Download and extract dependency package
before_build:
- ps: (new-object net.webclient).DownloadFile('https://github.com/projekter/dspdfviewer/releases/download/v1.14-42-g4acfb31/Dependencies.rar', 'c:\dependencies.rar')
- cmd: mkdir \dspdf
- cmd: 7z x -o\dspdf\poppler \dependencies.rar

# Build with cmake
build_script:
- cmd: mkdir build
- cmd: cd build
- cmd: cmake .. -G "Visual Studio 12 2013" -DUseQtFive=ON -DDownloadTestPDF=ON -DCMAKE_VERBOSE_MAKEFILE=ON
- cmd: cmake --build .

test_script:
- cmd: ctest --output-on-failure

# Un-Comment the PS script to get RDP shell after failure
on_failure:
- cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
- ps: '# $blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
