version: '{build}'
branches:
  only:
  - master
  - /^windows-test.*/
os: Visual Studio 2013

# Before build: Download and extract dependency package
before_build:
- ps: (new-object net.webclient).DownloadFile('https://github.com/projekter/dspdfviewer/releases/download/v1.14-42-g4acfb31/DependenciesDyn.rar', 'c:\dependencies.rar')
- cmd: cd \
- cmd: 7z x \dependencies.rar

# Build with cmake
build_script:
- cmd: cd \projects\dspdfviewer
- cmd: mkdir build
- cmd: cd build
- cmd: >
    cmake ..
    -G "Visual Studio 12 2013"
    -DUseQtFive=ON
    -DDownloadTestPDF=ON
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE_BUILD_TYPE=Debug
    -DBoostStaticLink=ON
    -DWindowsStaticLink=OFF
    -DBOOST_ROOT=\libraries\boost
    -DBOOST_LIBRARYDIR=\libraries\boost\lib32-msvc-12.0
- cmd: cmake --build .

test_script:
    - cmd: ctest -C Debug --output-on-failure

# Un-Comment this to get an RDP shell when something fails
#on_failure:
#- cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
#- ps: '$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
