version: '{build}'
branches:
  only:
  - master
  - /^test-.*/
os: Visual Studio 2013
configuration:
  - Debug
  - Release

# Before anything else: Download and extract dependency package
init:
- ps: (new-object net.webclient).DownloadFile('https://github.com/projekter/dspdfviewer/releases/download/v1.14-42-g4acfb31/DependenciesDyn.rar', 'c:\dependencies.rar')
- cmd: cd \
- cmd: 7z x \dependencies.rar
- cmd: cd \projects\dspdfviewer

# Before build: Let CMake create the solution file
before_build:
    - cmd: mkdir \projects\dspdfviewer\build
    - cmd: cd \projects\dspdfviewer\build
    - cmd: >
        cmake ..
        -G "Visual Studio 12 2013"
        -DUseQtFive=ON
        -DDownloadTestPDF=ON
        -DBoostStaticLink=ON
        -DWindowsStaticLink=OFF
        -DBOOST_ROOT=\libraries\boost
        -DBOOST_LIBRARYDIR=\libraries\boost\lib32-msvc-12.0

build:
  project: C:\projects\dspdfviewer\build\dspdfviewer.sln
  parallel: true
  verbosity: detailed

before_test:
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\cairo\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\expat\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\fontconfig\lib
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\freetype\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\lcms\lib\MS
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\libiconv\lib
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\libjpeg-turbo\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\libpng\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\libtiff\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\openjpeg\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\deps\zlib\bin
    - cmd: SET PATH=%PATH%;C:\dspdf\popplerDyn\poppler\bin
    - cmd: SET PATH=%PATH%;C:\qt\5.5\msvc2013\bin
    - cmd: if exist Testing\Debug copy C:\dspdf\popplerDyn\poppler\bin\poppler-qt5d.dll Testing\Debug\poppler-qt5.dll
    - cmd: if exist Testing\Debug copy C:\dspdf\popplerDyn\poppler\bin\poppler-qt5d.dll Testing\poppler-qt5.dll

after_test:
    - cmd: msbuild RUN_TESTS.vcxproj
