language: cpp
sudo: required
services:
    - docker
compiler:
    - clang
    - gcc
env:
    - CMAKE_PARAMETERS="-DUseQtFive=ON"
    - CMAKE_PARAMETERS="-DUseQtFive=OFF"
matrix:
  fast_finish: true
install:
 - _travis/install_dependencies
script:
 - _travis/compile
