language: cpp
compiler: gcc
sudo: false
cache: ccache
# define dependencies as q4dep and q5dep
qt4_deps: &q4dep
    - libboost-program-options-dev
    - libboost-test-dev
    - pkg-config
    - xvfb
    - xauth
    - libpoppler-qt4-dev
qt5_deps: &q5dep
    - libboost-program-options-dev
    - libboost-test-dev
    - pkg-config
    - xvfb
    - xauth
    - libpoppler-qt5-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
addons:
    apt:
        packages: *q4dep
env: QT_VERSION=4
# Only build master branch on push, other branches will get built when
# they are turned into pull-requests
branches:
    only:
        - master
        - /^test-.*$/
# Build matrix.
#
# 1. qt4/gcc @ precise
# 2. qt4/clang @ precise
# 3. qt5/gcc @ trusty
# 4. qt5/clang @ trusty
# 5. qt5/clang @ osx (default xcode)
# 6. qt5/gcc7 and clang-5.0 @ buster
# 7. qt5/gcc8 and clang-6.0 @ sid/experimental
matrix:
    include:
        - dist: precise
          compiler: gcc
        - dist: precise
          compiler: clang
        - dist: trusty
          sudo: required
          env: QT_VERSION=5
          compiler: gcc
          addons:
              apt:
                  packages: *q5dep
        - dist: trusty
          sudo: required
          env: QT_VERSION=5
          compiler: clang
          addons:
              apt:
                  packages: *q5dep
        - os: osx
          compiler: clang
          env: QT_VERSION=5
          before_install: _travis/osx-install-dependencies
        - services: docker
          addons:
              apt:
                  packages:
          env: DEBDIST=buster
          script:  _travis/docker/build-and-test-software
          install: _travis/docker/build-docker-image
        - services: docker
          addons:
              apt:
                  packages:
          env: DEBDIST=experimental
          script:  _travis/docker/build-and-test-software
          install: _travis/docker/build-docker-image
install:
    - _travis/configure
    - make -C build
script: _travis/test
after_success:
    - ccache -s
    - >
        if [[ "$CXX" == "clang++" && "$TRAVIS_OS_NAME" != "osx" ]] ; then
          bash <(curl -s https://codecov.io/bash) -x llvm-cov
        else
          bash <(curl -s https://codecov.io/bash)
        fi
