language: cpp
sudo: required
compiler:
    - clang
    - gcc
env:
    - CMAKE_PARAMETERS="-DUseQtFive=ON"
    - CMAKE_PARAMETERS="-DUseQtFive=OFF"
    - BUILDSYSTEM=debian DEPSYSTEM=debian
    - BUILDSYSTEM=outside
matrix:
  fast_finish: true
install:
 - _travis/install_dependencies
script:
 - _travis/compile
