language: cpp
sudo: required
services:
    - docker
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
env:
    - CMAKE_PARAMETERS="-DUseQtFive=ON"
    - CMAKE_PARAMETERS="-DUseQtFive=OFF"
matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: CMAKE_PARAMETERS="-DUseQtFive=ON"
    - os: osx
      compiler: gcc
  allow_failures:
      - os: osx
install:
 - _travis/install_dependencies
 - _travis/compile
script: _travis/test
