exclude:
  - vendor
  - Gemfile
  - Makefile

redcarpet:
  extensions:
    - autolink

# mimick github
# changeable
highlighter: pygments

# mimick github
# fixed
safe: true
lsi: false
source: .

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
