exclude:
  - vendor
  - Gemfile
  - Makefile

baseurl: "/dspdfviewer"

# mimick github
# changeable
highlighter: pygments

# mimick github
# fixed
safe: true
lsi: false
source: .

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
